# Generated by Django 3.2.7 on 2021-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=30, null=True)),
                ('group_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='createadmin',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='createadmin',
            name='UserName',
        ),
        migrations.AddField(
            model_name='createadmin',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='createadmin',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
