# Generated by Django 3.2.7 on 2021-10-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0002_auto_20211019_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=30, null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
