# Generated by Django 3.2.7 on 2021-10-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FormApp.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='location_name',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FormApp.location'),
        ),
    ]
