# Generated by Django 3.2.7 on 2021-10-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0006_auto_20211020_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_name',
            new_name='groupname',
        ),
    ]
