# Generated by Django 3.2.7 on 2021-10-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0009_auto_20211020_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
