# Generated by Django 3.2.7 on 2021-10-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0011_student_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='group_name',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='FormApp.group'),
        ),
    ]
