# Generated by Django 3.2.7 on 2021-10-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0012_alter_index_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groupname',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='FormApp.group'),
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
