# Generated by Django 3.2.7 on 2021-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0014_rename_groupname_student_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
        migrations.AddField(
            model_name='student',
            name='groupname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
