# Generated by Django 3.2.7 on 2021-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0015_auto_20211021_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
                ('student_name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
