# Generated by Django 3.2.7 on 2021-10-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0017_remove_student_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='remarks',
        ),
    ]
