# Generated by Django 3.2.7 on 2021-10-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0018_rename_email_student_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
