# Generated by Django 3.2.7 on 2021-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0020_auto_20211021_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, null=True)),
                ('student_name', models.CharField(max_length=30, null=True)),
                ('groupname', models.CharField(max_length=30, null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
