# Generated by Django 3.2.7 on 2021-10-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0022_auto_20211021_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Createadmin',
        ),
    ]
