# Generated by Django 3.2.7 on 2021-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0024_createadmin_group_index_location_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
    ]
