# Generated by Django 3.2.7 on 2021-10-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0025_remove_group_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
