# Generated by Django 3.2.7 on 2021-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0026_auto_20211021_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
