# Generated by Django 3.2.7 on 2021-10-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0028_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AlterField(
            model_name='student',
            name='groupname',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FormApp.group'),
        ),
    ]
