# Generated by Django 3.2.7 on 2021-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0029_auto_20211021_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='groupname',
            new_name='group_name',
        ),
    ]
