# Generated by Django 3.2.7 on 2021-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0032_alter_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
