# Generated by Django 3.2.7 on 2021-10-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0033_auto_20211021_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='studentname',
        ),
    ]
