# Generated by Django 3.2.7 on 2021-10-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0034_rename_student_name_student_studentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='groupname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remarks',
        ),
    ]
