# Generated by Django 3.2.7 on 2021-10-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0036_auto_20211021_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
