# Generated by Django 3.2.7 on 2021-10-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0037_remove_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
