# Generated by Django 3.2.7 on 2021-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0039_auto_20211022_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groupname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
