# Generated by Django 3.2.7 on 2021-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0040_alter_student_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
