# Generated by Django 3.2.7 on 2021-10-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0041_group_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='location_name',
            new_name='locationname',
        ),
    ]
